[workspace]
resolver = "2"
members = [
  "day-01",
  "day-02",
  "day-03",
  "day-04",
  "day-05",
  "day-06",
  "day-07",
  "day-08",
  "day-09",
  "day-10",
  "day-11",
]

[workspace.dependencies]
anyhow = "1.0.75"
derive_more = "0.99.17"
itertools = "0.12.0"
